name = "ai-dj"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SPOTIFY_CLIENT_ID = "28764b8a4f9d4021ba134256782ebd71"
SPOTIFY_CLIENT_SECRET = "e0acd708c1c6455fae4968a0689e7f27"

[[durable_objects.bindings]]
name = "DJ_STATE"
class_name = "DJState"

[[durable_objects.bindings]]
name = "USER_SESSIONS"
class_name = "UserSession"

[[migrations]]
tag = "v1"
new_classes = [ "DJState", "UserSession" ]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CACHE"
id = "b1a893b90c5c412f863b3c8fe66a9e34"

[[kv_namespaces]]
binding = "PLAYLISTS"
id = "1313f7f7b7744550b43d5b620f63f304"

[site]
bucket = "./public"